name: '天气预报'

on:
  watch:
    types: [started]
  schedule:
    - cron: '0 0-15 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install
      - run: node ./plugins/weather.js
        env:
          bot_api: ${{ secrets.bot_api }}
          tianapi_key: ${{ secrets.tianapi_key }}
          city: ${{ secrets.city }}