name: '微擎信息提醒'

on:
  watch:
    types: [started]
  schedule:
    - cron: '10 7 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install
      - run: node ./plugins/topnews.js
        env:
          bot_api: ${{ secrets.bot_api }}
          tianapi_key: ${{ secrets.tianapi_key }}